### ISSUE TITLE
A question about the efficiency

### ISSUE THREAD

**Issue by SipengXie** [ZenGo-X/emerald-city#15]
When I use `cargo test`, this project runs a little bit slowly. What may cause the problem?
`test_sign_n5_t2_ttag4 has been running for over 60 seconds`

**Comment by omershlo** [comment]
Hi, 
to be honest, its been a while since we updated this code. The protocol itself is slow and in this repo we made all sort of compromises since the goal was to enable the code to run in different environments. 
Can you try to see if this code: https://github.com/KZen-networks/multi-party-ecdsa helps you in your project?

**Comment by SipengXie** [comment]
Thank you!
